POST http://localhost:3000/api/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "sur_name": "Testovich",
    "login": "lalalla",
    "email": "test@example16.com",
    "password_hash": "user"
}